name: folio
description: Live portfolio developed in flutter 3.0.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # github
  github: ^9.2.0

  # web related
  flutter_html: any
  url_strategy: ^0.2.0
  universal_html: ^2.0.4

  # http
  http: ^1.0.0

  # utils
  mailto: ^2.0.0
  flip_card: ^0.6.0
  url_launcher: ^6.1.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.0.0

  # state management
  provider: ^6.0.5

  # cache
  shared_preferences: ^2.0.6

  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  intl: ^0.18.1

dependency_overrides:
  firebase_core_platform_interface: 4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/work/
    - assets/photos/
    - assets/services/
    - assets/projects/

    - data.json

  fonts:
    - family: Agustina
      fonts:
        - asset: fonts/agustina/agustina.otf
    
